// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwhrkyjslqrgflhwcphi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aHJreWpzbHFyZ2ZsaHdjcGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMTkwNzcsImV4cCI6MjA1Mzg5NTA3N30.cTtGm_nKUUZJB-3xqRcdFHxdDjCzBxpBDZv0Z7EKRBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);